/*
	* ==================================== *
		* Project: Nexus Client (Mapper)
		* File: mapper/src/common/data.h
		* Purpose: Embedded JAR byte array. Auto-generated by jar2header.py from nexus-client.jar.
		* Author: lolkit
	* ==================================== *
*/

#pragma once

#include <cstdint>
#include <cstddef>

namespace nexus 
{
    namespace data 
    {
        constexpr size_t JAR_SIZE = 0;
        constexpr uint8_t JAR_BYTES[] = { 0x0 };
    }
}